#!/usr/bin/env python

Import("env")
Import("env_modules")

env_vcr = env_modules.Clone()

# Godot source files

module_obj = []

env_vcr.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

